# Generated by Django 5.0.2 on 2025-07-14 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_agent', '0002_ongoinginstruction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailPollingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_history_id', models.CharField(blank=True, max_length=128, null=True)),
                ('last_polled', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=512, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=512, null=True)),
                ('token_uri', models.CharField(blank=True, max_length=512, null=True)),
                ('client_id', models.CharField(blank=True, max_length=512, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=512, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_polling_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
