# Generated by Django 5.0.2 on 2025-07-14 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_agent', '0003_gmailpollingstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoinginstruction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ongoinginstruction',
            name='status',
            field=models.CharField(default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='ongoinginstruction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
